### PR TITLE
Gui view improvement

### LINKED ISSUE #148: event.isCancelled = true seems asyncholized and will cause race condition in gui
The sponge api seems rollback the event in async.
So the following thing may happen

1. (Thread 1) slot changed by event hanlder in sponge
2. (Thread 1) receive event
3. (Thread 2) override the slot with the new GUI
4. **(Thread 1) event is cancelled, the slot was rollbacked unexpectedly**

### LINKED ISSUE #150: 快速點擊 GUI 能按到理論上已經不存在的按鈕
server 清除畫面到 client 收到新畫面中間有一段時差，在這個時差內狂按。就有機會翻到選單變超出頁數

### PR DESCRIPTION
**Pull request by mmis1000**
Improve the gui
 - [x] delay inventory edit until next tick to ensure it won't break
 - [x] make user able to move item in their backpack when using gui (only the parts currently write with view)
 - [x] remove uuid related stuff from view becuase `SlotIndex` works now
 - [x] add method to get detail of a event 
   - [x] will it affect gui or not? 
   - [x] what slot is affected? 
   - [x] what is the data the slot contains?

closes #148 , closes #150

### CODE REVIEW

File: src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt [hunk 1]
```diff
@@ -47,73 +46,80 @@ class BrowserGalaxy(player: Player? = null) : PageGUI() {
...
+            event.isCancelled = true
+        }
 
-        if (view.getNameOf(uuid)?.first == Companion.Slot.ITEMS) {
-            launch {
-                galaxyManager.get(uuid)?.let {
-                    GUIHelper.open(player) { GalaxyInfo(it, player) }
+        if (detail.primary?.type == Companion.Slot.ITEMS) {
+            val player = event.source as Player
+            val uuid = detail.primary.data?.data
```
Comment (james58899) [inline src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt]: 像其他地方介面一樣null直接return?

Comment (mmis1000) [reply src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt]: 像哪邊null直接?

**Comment by mmis1000** [comment]
@james58899 fixed
